---
apiVersion: v1
kind: Namespace
metadata:
  name: loki
spec: {}
status: {}

---
apiVersion: v1
kind: Secret
metadata:
  name: loki-s3-credentials
  namespace: loki
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "YOUR_ACTUAL_ACCESS_KEY"
  AWS_SECRET_ACCESS_KEY: "YOUR_ACTUAL_SECRET_KEY"
